### ISSUE TITLE
Bundle install error

### ISSUE THREAD

**Issue by shantilal-narola** [mak-it/omniauth-latvija#3]
facing issue while bundle install:

C239s-iMac:agreementsignature c239$ bundle install
The git source `git://github.com/activeadmin/activeadmin.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/activeadmin/inherited_resources.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/thoughtbot/paperclip.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Your bundle requires gems that depend on each other, creating an infinite loop. Please remove gem 'canonix' and try again.

**Comment by ebeigarts** [comment]
The `canonix` gem is broken, you can avoid this by using older bundler `< 1.9` - `gem install bundler -v '< 1.9'`. We should probably switch to `nokogiri` for canonicalisation, since `canonix` is not maintained.

**Comment by ebeigarts** [comment]
This has been fixed in #4 by switching to nokogiri.
